### ISSUE TITLE
Copy Editing

### ISSUE THREAD

**Issue by jeremylt** [Eudicods/outworlds-wastes#115]
Copy editing for grammar is welcome.

Any of the .tex files in the `rules` folder and any numbered subfolders can receive grammar edits.
Source files can be found here:
https://github.com/Eudicods/outworlds-wastes/tree/main/rules

I may end up tweaking any edits you propose, to meet layout goals in the generated PDFs.

Note: The website and PDFs are built using LaTex. You do not need to futz with LaTeX. The built website source is on the `rules-web` branch:
https://github.com/Eudicods/outworlds-wastes/tree/rules-web

If you have questions, you can ask here, but for a more realtime back and forth, you can find me on the freeCodeCamp Discord:
https://www.freecodecamp.org/news/freecodecamp-discord-chat-room-server/

**Comment by mendoncamaria** [comment]
Hi. What exactly do you need help with in this particular issue? If it is related to grammatical corrections, I can take it up. Thanks!

**Comment by mendoncamaria** [comment]
Ok. I want to take this up. What are the contributing guidelines? and will you assign this issue? What about the labels?

**Comment by mendoncamaria** [comment]
And i did observe the Contributing.md file can have some more details on naming conventions and more details on steps for raise PR. If you're ok, I would like to take that up too.

**Comment by jeremylt** [comment]
I'm pretty relaxed with branch and PR naming conventions. But if you have suggestions for the contributing file, please feel free.


I'll have to run the local build process to check formatting, so the process is that you propose changes on your fork, make a PR to this repo, then I check the PDFs and propose any formatting changes needed.

**Comment by mendoncamaria** [comment]
@jeremylt I have updated two files for starter. Let me know what you think. If this looks good, I'll go ahead with other files.

**Comment by jeremylt** [comment]
That looks like some pretty extensive rewriting of the text?

**Comment by mendoncamaria** [comment]
> That looks like some pretty extensive rewriting of the text instead of only typo and grammar fixes?

Yes. I thought rewriting would make it look more neat and appealing. But if you don't want to rewrite, I can check for typos.

**Comment by jeremylt** [comment]
It would be substantially easier to review only corrections for typos and grammar errors rather than a full rewrite of everything.
