### ISSUE TITLE
Responsive image issue

### ISSUE THREAD

**Issue by jeremylt** [Eudicods/outworlds-wastes#120]
The images like this one here weren't caught in the last responsive fix:

https://github.com/Eudicods/outworlds-wastes/blob/rules-web/short-story.html#L233

These images spill to the right in mobile view: figure>p>a>img. Probably should target these in addition to figure>p>img

The CSS file here should be updated for better responsiveness:
https://github.com/Eudicods/outworlds-wastes/blob/main/rules/style.css

Note: This website is built using LaTex. You do not need to futz with LaTeX. The built website source is on the rules-web branch:
https://github.com/Eudicods/outworlds-wastes/tree/rules-web

If you have questions, you can ask here, but for a more realtime back and forth, you can find me on the freeCodeCamp Discord:
https://www.freecodecamp.org/news/freecodecamp-discord-chat-room-server/

See previous discussion in https://github.com/Eudicods/outworlds-wastes/issues/113#issuecomment-2387552019_

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by jeremylt** [comment]
Go for it

**Comment by jeremylt** [comment]
How's this coming @uzefaqureshi06?
