### ISSUE TITLE
Update CONTRIBUTING.md file

### ISSUE THREAD

**Issue by mendoncamaria** [Eudicods/outworlds-wastes#125]
The file regarding contributing to the repository is not up to date. It lacks guidelines on raising PRs, PR titles, and comments to add while raising an issue or getting an issue assigned to oneself.   

**Requested Changes:**
- Add clear and concise guidelines on how to raise a PR.
- Include instructions on how to format PR titles effectively.
- Provide guidance on what comments to include when raising an issue or requesting an issue be assigned to oneself.

<br />

**Additional Notes:**
- The updated guidelines should be easily accessible and understandable to contributors of all levels.
- The guidelines should be consistent with the overall style and tone of the repository's documentation.

**Comment by Sridevi0321** [comment]
I would like to contribute to the CONTRIBUTING.md file. Can you please assign this issue to me?
