### ISSUE TITLE
Issue: Base Defense Mission - Alpha Strike Conversion for Heights

### ISSUE THREAD

**Issue by OftKilted** [Eudicods/outworlds-wastes#97]
The Base defense mission is using unusual height conversions from classic to Alpha Strike.

“5.9.1 Primary Objectives

Base Defense: 7 buildings are on the defenders side of the map. Each building is medium with a construction factor of 60 (6, Alpha Strike) and **1-3 levels high (2"-6", Alpha Strike)**, unless the players agree upon a different configuration.”

This seems out of sync with unit heights. One level in Alpha Strike is half a mech high, as mechs are 2 levels. This would appear to translate to 1”-3” high, not 2” to 6”.

The “Alpha Strike to hex map play” conversion page lists it as “The core conversion between Alpha Strike terrain play, and hex map rules, is 2” per 1 hex and 1” per 1 level of elevation.” p.68 AS:CE

**Comment by jeremylt** [comment]
Thanks for catching this. Fixed in https://github.com/Eudicods/outworlds-wastes/pull/99
